fragment packageContent on Package {
  name
  description
  version
  author
  license
  dependencies {
    name
    version
  }
  devDependencies{
    name
    version
  }
}

fragment unusedFragment on Package {
  name
}

query fetchPackage {
  fetchPackage {
    ...packageContent
  }
}

query fetchPackageName {
  fetchPackage {
    name
  }
}

mutation updatePackage ($pkg: PackageIn!) {
  updatePackage (pkg: $pkg) {
    ...packageContent
  }
}

mutation updatePackageNoResult ($pkg: PackageIn!) {
  updatePackageNoReturn (pkg: $pkg)
}

