query fetchPackage {
  fetchPackage {
    name
    description
    version
    author
    license
    dependencies {
      name
      version
    }
    devDependencies{
      name
      version
    }
    peerDependencies{
      name
      version
    }
  }
}

mutation updatePackage ($pkg: PackageIn!) {
  updatePackage (pkg: $pkg) {
    name
    description
    version
    author
    license
    dependencies {
      name
      version
    }
    devDependencies{
      name
      version
    }
    peerDependencies{
      name
      version
    }
  }
}
